### ISSUE TITLE
name

### ISSUE THREAD

**Issue by untzag** [wright-group/yaq#2]
what shall we name this thing?

all lowercase please

the following names are not taken on PyPI or anaconda-cloud (roughly ordered according to my preference):
- pyaq
- acquire
- maestropy
- labcontrol

**Comment by darienmorrow** [comment]
pytroscopy

**Comment by darienmorrow** [comment]
As suggested by @untzag: yaq. yet another acquisition

**Comment by ksunden** [comment]
I believe we have settled on yaq. Closing the issue, if further discussion is warranted, please reopen... (I hope no further discussion is needed...)
